[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
config = { path = "../config" }
tokio = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
arboard = { workspace = true }
rusqlite = { workspace = true }
xcb = { workspace = true }
image = { workspace = true }
notify-rust = { workspace = true }
sha2 = { workspace = true }
dirs = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }

[dev-dependencies]
tempfile = "3"
