use crate::inputs::KeybdKey::OtherKey;

pub enum KeybdKey {
    BackspaceKey,
    TabKey,
    EnterKey,
    EscapeKey,
    SpaceKey,
    PageUpKey,
    PageDownKey,
    EndKey,
    HomeKey,
    LeftKey,
    UpKey,
    RightKey,
    DownKey,
    InsertKey,
    DeleteKey,
    Numrow0Key,
    Numrow1Key,
    Numrow2Key,
    Numrow3Key,
    Numrow4Key,
    Numrow5Key,
    Numrow6Key,
    Numrow7Key,
    Numrow8Key,
    Numrow9Key,
    AKey,
    BKey,
    CKey,
    DKey,
    EKey,
    FKey,
    GKey,
    HKey,
    IKey,
    JKey,
    KKey,
    LKey,
    MKey,
    NKey,
    OKey,
    PKey,
    QKey,
    RKey,
    SKey,
    TKey,
    UKey,
    VKey,
    WKey,
    XKey,
    YKey,
    ZKey,
    LSuper,
    RSuper,
    Numpad0Key,
    Numpad1Key,
    Numpad2Key,
    Numpad3Key,
    Numpad4Key,
    Numpad5Key,
    Numpad6Key,
    Numpad7Key,
    Numpad8Key,
    Numpad9Key,
    F1Key,
    F2Key,
    F3Key,
    F4Key,
    F5Key,
    F6Key,
    F7Key,
    F8Key,
    F9Key,
    F10Key,
    F11Key,
    F12Key,
    F13Key,
    F14Key,
    F15Key,
    F16Key,
    F17Key,
    F18Key,
    F19Key,
    F20Key,
    F21Key,
    F22Key,
    F23Key,
    F24Key,
    NumLockKey,
    ScrollLockKey,
    CapsLockKey,
    LShiftKey,
    RShiftKey,
    LControlKey,
    RControlKey,
    LAltKey,
    RAltKey,

    BrowserBackKey,
    BrowserForwardKey,
    BrowserRefreshKey,

    VolumeMuteKey,
    VolumeDownKey,
    VolumeUpKey,

    MediaNextTrackKey,
    MediaPrevTrackKey,
    MediaStopKey,
    MediaPlayPauseKey,

    BackquoteKey,
    SlashKey,
    BackslashKey,
    CommaKey,
    PeriodKey,
    MinusKey,
    QuoteKey,
    SemicolonKey,
    LBracketKey,
    RBracketKey,
    EqualKey,
    OtherKey(u64)
}


impl From<KeybdKey> for u64 {
    // https://www.cl.cam.ac.uk/~mgk25/ucs/keysymdef.h
    // https://github.com/AltF02/x11-rs/blob/master/src/keysym.rs
    fn from(key: KeybdKey) -> u64 {
        match key {
            KeybdKey::BackspaceKey => 0xFF08,
            KeybdKey::TabKey => 0xFF09,
            KeybdKey::EnterKey => 0xFF8D,
            KeybdKey::EscapeKey => 0xFF1B,
            KeybdKey::SpaceKey => 0x020,
            KeybdKey::PageUpKey => 0xFF55,
            KeybdKey::PageDownKey => 0xFF56,
            KeybdKey::EndKey => 0xFF57,
            KeybdKey::HomeKey => 0xFF50,
            KeybdKey::LeftKey => 0xFF51,
            KeybdKey::UpKey => 0xFF52,
            KeybdKey::RightKey => 0xFF53,
            KeybdKey::DownKey => 0xFF54,
            KeybdKey::InsertKey => 0xFF63,
            KeybdKey::DeleteKey => 0xFF9F,
            KeybdKey::Numrow0Key => 0x030,
            KeybdKey::Numrow1Key => 0x031,
            KeybdKey::Numrow2Key => 0x032,
            KeybdKey::Numrow3Key => 0x033,
            KeybdKey::Numrow4Key => 0x034,
            KeybdKey::Numrow5Key => 0x035,
            KeybdKey::Numrow6Key => 0x036,
            KeybdKey::Numrow7Key => 0x037,
            KeybdKey::Numrow8Key => 0x038,
            KeybdKey::Numrow9Key => 0x039,
            KeybdKey::AKey => 0x041,
            KeybdKey::BKey => 0x042,
            KeybdKey::CKey => 0x043,
            KeybdKey::DKey => 0x044,
            KeybdKey::EKey => 0x045,
            KeybdKey::FKey => 0x046,
            KeybdKey::GKey => 0x047,
            KeybdKey::HKey => 0x048,
            KeybdKey::IKey => 0x049,
            KeybdKey::JKey => 0x04A,
            KeybdKey::KKey => 0x04B,
            KeybdKey::LKey => 0x04C,
            KeybdKey::MKey => 0x04D,
            KeybdKey::NKey => 0x04E,
            KeybdKey::OKey => 0x04F,
            KeybdKey::PKey => 0x050,
            KeybdKey::QKey => 0x051,
            KeybdKey::RKey => 0x052,
            KeybdKey::SKey => 0x053,
            KeybdKey::TKey => 0x054,
            KeybdKey::UKey => 0x055,
            KeybdKey::VKey => 0x056,
            KeybdKey::WKey => 0x057,
            KeybdKey::XKey => 0x058,
            KeybdKey::YKey => 0x059,
            KeybdKey::ZKey => 0x05A,
            KeybdKey::LSuper => 0xFFEB,
            KeybdKey::RSuper => 0xFFEC,
            KeybdKey::Numpad0Key => 0xFFB0,
            KeybdKey::Numpad1Key => 0xFFB1,
            KeybdKey::Numpad2Key => 0xFFB2,
            KeybdKey::Numpad3Key => 0xFFB3,
            KeybdKey::Numpad4Key => 0xFFB4,
            KeybdKey::Numpad5Key => 0xFFB5,
            KeybdKey::Numpad6Key => 0xFFB6,
            KeybdKey::Numpad7Key => 0xFFB7,
            KeybdKey::Numpad8Key => 0xFFB8,
            KeybdKey::Numpad9Key => 0xFFB9,
            KeybdKey::F1Key => 0xFFBE,
            KeybdKey::F2Key => 0xFFBF,
            KeybdKey::F3Key => 0xFFC0,
            KeybdKey::F4Key => 0xFFC1,
            KeybdKey::F5Key => 0xFFC2,
            KeybdKey::F6Key => 0xFFC3,
            KeybdKey::F7Key => 0xFFC4,
            KeybdKey::F8Key => 0xFFC5,
            KeybdKey::F9Key => 0xFFC6,
            KeybdKey::F10Key => 0xFFC7,
            KeybdKey::F11Key => 0xFFC8,
            KeybdKey::F12Key => 0xFFC9,
            KeybdKey::F13Key => 0xFFCA,
            KeybdKey::F14Key => 0xFFCB,
            KeybdKey::F15Key => 0xFFCC,
            KeybdKey::F16Key => 0xFFCD,
            KeybdKey::F17Key => 0xFFCE,
            KeybdKey::F18Key => 0xFFCF,
            KeybdKey::F19Key => 0xFFD0,
            KeybdKey::F20Key => 0xFFD1,
            KeybdKey::F21Key => 0xFFD2,
            KeybdKey::F22Key => 0xFFD3,
            KeybdKey::F23Key => 0xFFD4,
            KeybdKey::F24Key => 0xFFD5,
            KeybdKey::NumLockKey => 0xFF7F,
            KeybdKey::ScrollLockKey => 0xFF14,
            KeybdKey::CapsLockKey => 0xFFE5,
            KeybdKey::LShiftKey => 0xFFE1,
            KeybdKey::RShiftKey => 0xFFE2,
            KeybdKey::LControlKey => 0xFFE3,
            KeybdKey::RControlKey => 0xFFE4,
            KeybdKey::LAltKey => 0xFFE9,
            KeybdKey::RAltKey => 0xFFEA,
            KeybdKey::BrowserBackKey => 0x1008FF26,
            KeybdKey::BrowserForwardKey => 0x1008FF27,
            KeybdKey::BrowserRefreshKey => 0x1008FF29,
            KeybdKey::VolumeMuteKey => 0x1008FF12,
            KeybdKey::VolumeDownKey => 0x1008FF11,
            KeybdKey::VolumeUpKey => 0x1008FF13,
            KeybdKey::MediaNextTrackKey => 0x1008FF17,
            KeybdKey::MediaPrevTrackKey => 0x1008FF16,
            KeybdKey::MediaStopKey => 0x1008FF15,
            KeybdKey::MediaPlayPauseKey => 0x1008FF14,
            KeybdKey::BackquoteKey => 0x29,
            KeybdKey::SlashKey => 0x35,
            KeybdKey::BackslashKey => 0x2B,
            KeybdKey::CommaKey => 0x33,
            KeybdKey::PeriodKey => 0x34,
            KeybdKey::MinusKey => 0x0C,
            KeybdKey::QuoteKey => 0x28,
            KeybdKey::SemicolonKey => 0x27,
            KeybdKey::LBracketKey => 0x1A,
            KeybdKey::RBracketKey => 0x1B,
            KeybdKey::EqualKey => 0x0D,
            _ => 0x0
        }
    }
}

impl From<u64> for KeybdKey {
    // https://www.cl.cam.ac.uk/~mgk25/ucs/keysymdef.h
    // https://github.com/AltF02/x11-rs/blob/master/src/keysym.rs
    fn from(code: u64) -> KeybdKey {
        match code {
            0xFF08 =>KeybdKey::BackspaceKey,
            0xFF09 =>KeybdKey::TabKey,
            0xFF8D =>KeybdKey::EnterKey,
            0xFF1B =>KeybdKey::EscapeKey,
            0x020 =>KeybdKey::SpaceKey,
            0xFF55 =>KeybdKey::PageUpKey,
            0xFF56 =>KeybdKey::PageDownKey,
            0xFF57 =>KeybdKey::EndKey,
            0xFF50 =>KeybdKey::HomeKey,
            0xFF51 =>KeybdKey::LeftKey,
            0xFF52 =>KeybdKey::UpKey,
            0xFF53 =>KeybdKey::RightKey,
            0xFF54 =>KeybdKey::DownKey,
            0xFF63 =>KeybdKey::InsertKey,
            0xFF9F =>KeybdKey::DeleteKey,
            0x030 =>KeybdKey::Numrow0Key,
            0x031 =>KeybdKey::Numrow1Key,
            0x032 =>KeybdKey::Numrow2Key,
            0x033 =>KeybdKey::Numrow3Key,
            0x034 =>KeybdKey::Numrow4Key,
            0x035 =>KeybdKey::Numrow5Key,
            0x036 =>KeybdKey::Numrow6Key,
            0x037 =>KeybdKey::Numrow7Key,
            0x038 =>KeybdKey::Numrow8Key,
            0x039 =>KeybdKey::Numrow9Key,
            0x041 =>KeybdKey::AKey,
            0x042 =>KeybdKey::BKey,
            0x043 =>KeybdKey::CKey,
            0x044 =>KeybdKey::DKey,
            0x045 =>KeybdKey::EKey,
            0x046 =>KeybdKey::FKey,
            0x047 =>KeybdKey::GKey,
            0x048 =>KeybdKey::HKey,
            0x049 =>KeybdKey::IKey,
            0x04A =>KeybdKey::JKey,
            0x04B =>KeybdKey::KKey,
            0x04C =>KeybdKey::LKey,
            0x04D =>KeybdKey::MKey,
            0x04E =>KeybdKey::NKey,
            0x04F =>KeybdKey::OKey,
            0x050 =>KeybdKey::PKey,
            0x051 =>KeybdKey::QKey,
            0x052 =>KeybdKey::RKey,
            0x053 =>KeybdKey::SKey,
            0x054 =>KeybdKey::TKey,
            0x055 =>KeybdKey::UKey,
            0x056 =>KeybdKey::VKey,
            0x057 =>KeybdKey::WKey,
            0x058 =>KeybdKey::XKey,
            0x059 =>KeybdKey::YKey,
            0x05A =>KeybdKey::ZKey,
            0xFFEB =>KeybdKey::LSuper,
            0xFFEC =>KeybdKey::RSuper,
            0xFFB0 =>KeybdKey::Numpad0Key,
            0xFFB1 =>KeybdKey::Numpad1Key,
            0xFFB2 =>KeybdKey::Numpad2Key,
            0xFFB3 =>KeybdKey::Numpad3Key,
            0xFFB4 =>KeybdKey::Numpad4Key,
            0xFFB5 =>KeybdKey::Numpad5Key,
            0xFFB6 =>KeybdKey::Numpad6Key,
            0xFFB7 =>KeybdKey::Numpad7Key,
            0xFFB8 =>KeybdKey::Numpad8Key,
            0xFFB9 =>KeybdKey::Numpad9Key,
            0xFFBE =>KeybdKey::F1Key,
            0xFFBF =>KeybdKey::F2Key,
            0xFFC0 =>KeybdKey::F3Key,
            0xFFC1 =>KeybdKey::F4Key,
            0xFFC2 =>KeybdKey::F5Key,
            0xFFC3 =>KeybdKey::F6Key,
            0xFFC4 =>KeybdKey::F7Key,
            0xFFC5 =>KeybdKey::F8Key,
            0xFFC6 =>KeybdKey::F9Key,
            0xFFC7 =>KeybdKey::F10Key,
            0xFFC8 =>KeybdKey::F11Key,
            0xFFC9 =>KeybdKey::F12Key,
            0xFFCA =>KeybdKey::F13Key,
            0xFFCB =>KeybdKey::F14Key,
            0xFFCC =>KeybdKey::F15Key,
            0xFFCD =>KeybdKey::F16Key,
            0xFFCE =>KeybdKey::F17Key,
            0xFFCF =>KeybdKey::F18Key,
            0xFFD0 =>KeybdKey::F19Key,
            0xFFD1 =>KeybdKey::F20Key,
            0xFFD2 =>KeybdKey::F21Key,
            0xFFD3 =>KeybdKey::F22Key,
            0xFFD4 =>KeybdKey::F23Key,
            0xFFD5 =>KeybdKey::F24Key,
            0xFF7F =>KeybdKey::NumLockKey,
            0xFF14 =>KeybdKey::ScrollLockKey,
            0xFFE5 =>KeybdKey::CapsLockKey,
            0xFFE1 =>KeybdKey::LShiftKey,
            0xFFE2 =>KeybdKey::RShiftKey,
            0xFFE3 =>KeybdKey::LControlKey,
            0xFFE4 =>KeybdKey::RControlKey,
            0xFFE9 =>KeybdKey::LAltKey,
            0xFFEA =>KeybdKey::RAltKey,
            0x1008FF26 =>KeybdKey::BrowserBackKey,
            0x1008FF27 =>KeybdKey::BrowserForwardKey,
            0x1008FF29 =>KeybdKey::BrowserRefreshKey,
            0x1008FF12 =>KeybdKey::VolumeMuteKey,
            0x1008FF11 =>KeybdKey::VolumeDownKey,
            0x1008FF13 =>KeybdKey::VolumeUpKey,
            0x1008FF17 =>KeybdKey::MediaNextTrackKey,
            0x1008FF16 =>KeybdKey::MediaPrevTrackKey,
            0x1008FF15 =>KeybdKey::MediaStopKey,
            0x1008FF14 =>KeybdKey::MediaPlayPauseKey,
            0x29 =>KeybdKey::BackquoteKey,
            0x35 =>KeybdKey::SlashKey,
            0x2B =>KeybdKey::BackslashKey,
            0x33 =>KeybdKey::CommaKey,
            0x34 =>KeybdKey::PeriodKey,
            0x0C =>KeybdKey::MinusKey,
            0x28 =>KeybdKey::QuoteKey,
            0x27 =>KeybdKey::SemicolonKey,
            0x1A =>KeybdKey::LBracketKey,
            0x1B =>KeybdKey::RBracketKey,
            0x0D =>KeybdKey::EqualKey,

            _ => OtherKey(code)
        }
    }
}


// https://www.win.tue.nl/~aeb/linux/kbd/scancodes-1.html
pub fn scan_code_to_key(scan_code: u32) -> Option<KeybdKey> {
    match scan_code {
        0x0E => Some(KeybdKey::BackspaceKey),
        0x0F => Some(KeybdKey::TabKey),
        0x1C => Some(KeybdKey::EnterKey),
        0x01 => Some(KeybdKey::EscapeKey),
        0x39 => Some(KeybdKey::SpaceKey),
        0x47 => Some(KeybdKey::HomeKey),
        0x4B => Some(KeybdKey::LeftKey),
        0x48 => Some(KeybdKey::UpKey),
        0x4D => Some(KeybdKey::RightKey),
        0x50 => Some(KeybdKey::DownKey),
        0x52 => Some(KeybdKey::InsertKey),
        0x53 => Some(KeybdKey::DeleteKey),
        0x0B => Some(KeybdKey::Numrow0Key),
        0x02 => Some(KeybdKey::Numrow1Key),
        0x03 => Some(KeybdKey::Numrow2Key),
        0x04 => Some(KeybdKey::Numrow3Key),
        0x05 => Some(KeybdKey::Numrow4Key),
        0x06 => Some(KeybdKey::Numrow5Key),
        0x07 => Some(KeybdKey::Numrow6Key),
        0x08 => Some(KeybdKey::Numrow7Key),
        0x09 => Some(KeybdKey::Numrow8Key),
        0x0A => Some(KeybdKey::Numrow9Key),
        0x1E => Some(KeybdKey::AKey),
        0x30 => Some(KeybdKey::BKey),
        0x2E => Some(KeybdKey::CKey),
        0x20 => Some(KeybdKey::DKey),
        0x12 => Some(KeybdKey::EKey),
        0x21 => Some(KeybdKey::FKey),
        0x22 => Some(KeybdKey::GKey),
        0x23 => Some(KeybdKey::HKey),
        0x17 => Some(KeybdKey::IKey),
        0x24 => Some(KeybdKey::JKey),
        0x25 => Some(KeybdKey::KKey),
        0x26 => Some(KeybdKey::LKey),
        0x32 => Some(KeybdKey::MKey),
        0x31 => Some(KeybdKey::NKey),
        0x18 => Some(KeybdKey::OKey),
        0x19 => Some(KeybdKey::PKey),
        0x10 => Some(KeybdKey::QKey),
        0x13 => Some(KeybdKey::RKey),
        0x1F => Some(KeybdKey::SKey),
        0x14 => Some(KeybdKey::TKey),
        0x16 => Some(KeybdKey::UKey),
        0x2F => Some(KeybdKey::VKey),
        0x11 => Some(KeybdKey::WKey),
        0x2D => Some(KeybdKey::XKey),
        0x15 => Some(KeybdKey::YKey),
        0x2C => Some(KeybdKey::ZKey),
        0x52 => Some(KeybdKey::Numpad0Key),
        0x4F => Some(KeybdKey::Numpad1Key),
        0x50 => Some(KeybdKey::Numpad2Key),
        0x51 => Some(KeybdKey::Numpad3Key),
        0x4B => Some(KeybdKey::Numpad4Key),
        0x4C => Some(KeybdKey::Numpad5Key),
        0x4D => Some(KeybdKey::Numpad6Key),
        0x47 => Some(KeybdKey::Numpad7Key),
        0x48 => Some(KeybdKey::Numpad8Key),
        0x49 => Some(KeybdKey::Numpad9Key),
        0x3B => Some(KeybdKey::F1Key),
        0x3C => Some(KeybdKey::F2Key),
        0x3D => Some(KeybdKey::F3Key),
        0x3E => Some(KeybdKey::F4Key),
        0x3F => Some(KeybdKey::F5Key),
        0x40 => Some(KeybdKey::F6Key),
        0x41 => Some(KeybdKey::F7Key),
        0x42 => Some(KeybdKey::F8Key),
        0x43 => Some(KeybdKey::F9Key),
        0x44 => Some(KeybdKey::F10Key),
        0x45 => Some(KeybdKey::NumLockKey),
        0x46 => Some(KeybdKey::ScrollLockKey),
        0x3A => Some(KeybdKey::CapsLockKey),
        0x2A => Some(KeybdKey::LShiftKey),
        0x36 => Some(KeybdKey::RShiftKey),
        0x1D => Some(KeybdKey::LControlKey),
        0x29 => Some(KeybdKey::BackquoteKey),
        0x35 => Some(KeybdKey::SlashKey),
        0x2B => Some(KeybdKey::BackslashKey),
        0x33 => Some(KeybdKey::CommaKey),
        0x34 => Some(KeybdKey::PeriodKey),
        0x0C => Some(KeybdKey::MinusKey),
        0x28 => Some(KeybdKey::QuoteKey),
        0x27 => Some(KeybdKey::SemicolonKey),
        0x1A => Some(KeybdKey::LBracketKey),
        0x1B => Some(KeybdKey::RBracketKey),
        0x0D => Some(KeybdKey::EqualKey),
        _ => None,
    }
}

// https://www.win.tue.nl/~aeb/linux/kbd/scancodes-1.html
pub fn key_to_scan_code(key: KeybdKey) -> i32 {
    match key {
        KeybdKey::BackspaceKey => 0x0E,
        KeybdKey::TabKey => 0x0F,
        KeybdKey::EnterKey => 0x1C,
        KeybdKey::EscapeKey => 0x01,
        KeybdKey::SpaceKey => 0x39,
        KeybdKey::HomeKey => 0x47,
        KeybdKey::LeftKey => 0x4b,
        KeybdKey::UpKey => 0x48,
        KeybdKey::RightKey => 0x4D,
        KeybdKey::DownKey => 0x50,
        KeybdKey::InsertKey => 0x52,
        KeybdKey::DeleteKey => 0x53,
        KeybdKey::Numrow0Key => 0x0B,
        KeybdKey::Numrow1Key => 0x02,
        KeybdKey::Numrow2Key => 0x03,
        KeybdKey::Numrow3Key => 0x04,
        KeybdKey::Numrow4Key => 0x05,
        KeybdKey::Numrow5Key => 0x06,
        KeybdKey::Numrow6Key => 0x07,
        KeybdKey::Numrow7Key => 0x08,
        KeybdKey::Numrow8Key => 0x09,
        KeybdKey::Numrow9Key => 0x0A,
        KeybdKey::AKey => 0x1E,
        KeybdKey::BKey => 0x30,
        KeybdKey::CKey => 0x2E,
        KeybdKey::DKey => 0x20,
        KeybdKey::EKey => 0x12,
        KeybdKey::FKey => 0x21,
        KeybdKey::GKey => 0x22,
        KeybdKey::HKey => 0x23,
        KeybdKey::IKey => 0x17,
        KeybdKey::JKey => 0x24,
        KeybdKey::KKey => 0x25,
        KeybdKey::LKey => 0x26,
        KeybdKey::MKey => 0x32,
        KeybdKey::NKey => 0x31,
        KeybdKey::OKey => 0x18,
        KeybdKey::PKey => 0x19,
        KeybdKey::QKey => 0x10,
        KeybdKey::RKey => 0x13,
        KeybdKey::SKey => 0x1F,
        KeybdKey::TKey => 0x14,
        KeybdKey::UKey => 0x16,
        KeybdKey::VKey => 0x2F,
        KeybdKey::WKey => 0x11,
        KeybdKey::XKey => 0x2D,
        KeybdKey::YKey => 0x15,
        KeybdKey::ZKey => 0x2C,
        KeybdKey::Numpad0Key => 0x52,
        KeybdKey::Numpad1Key => 0x4F,
        KeybdKey::Numpad2Key => 0x50,
        KeybdKey::Numpad3Key => 0x51,
        KeybdKey::Numpad4Key => 0x4B,
        KeybdKey::Numpad5Key => 0x4C,
        KeybdKey::Numpad6Key => 0x4D,
        KeybdKey::Numpad7Key => 0x47,
        KeybdKey::Numpad8Key => 0x48,
        KeybdKey::Numpad9Key => 0x49,
        KeybdKey::F1Key => 0x3B,
        KeybdKey::F2Key => 0x3C,
        KeybdKey::F3Key => 0x3D,
        KeybdKey::F4Key => 0x3E,
        KeybdKey::F5Key => 0x3F,
        KeybdKey::F6Key => 0x40,
        KeybdKey::F7Key => 0x41,
        KeybdKey::F8Key => 0x42,
        KeybdKey::F9Key => 0x43,
        KeybdKey::F10Key => 0x44,
        KeybdKey::NumLockKey => 0x45,
        KeybdKey::ScrollLockKey => 0x46,
        KeybdKey::CapsLockKey => 0x3A,
        KeybdKey::LShiftKey => 0x2A,
        KeybdKey::RShiftKey => 0x36,
        KeybdKey::LControlKey => 0x1D,
        KeybdKey::BackquoteKey => 0x29,
        KeybdKey::SlashKey => 0x35,
        KeybdKey::BackslashKey => 0x2B,
        KeybdKey::CommaKey => 0x33,
        KeybdKey::PeriodKey => 0x34,
        KeybdKey::MinusKey => 0x0C,
        KeybdKey::QuoteKey => 0x28,
        KeybdKey::SemicolonKey => 0x27,
        KeybdKey::LBracketKey => 0x1A,
        KeybdKey::RBracketKey => 0x1B,
        KeybdKey::EqualKey => 0x0D,
        KeybdKey::OtherKey(code) => code as i32,
        _ => 0x0,
    }
}

